// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "title": "Netra Niti",
  "homepage": {
    "heroSection": {
      "title": "Focus on what matters with",
      "secondaryTitle": "clear vision.",
      "description": "Personalized eye care and the latest in fashionable eyewear, all under one roof.",
      "ctaButton": "Book an eye exam"
    }
  }
};
export default messages;